// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfuCyN14tMEmBWHwlaHv-ePzN8_gOt1Y0',
    appId: '1:1038188114074:web:5ae873c881132f1672af23',
    messagingSenderId: '1038188114074',
    projectId: 'rndvouz-uh',
    authDomain: 'rndvouz-uh.firebaseapp.com',
    storageBucket: 'rndvouz-uh.appspot.com',
    measurementId: 'G-9CJG5YQ5CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv9v6hiCwMgDwm8A2olU0XVhNtcU5bANs',
    appId: '1:1038188114074:android:7b8f30ce8f2f27c972af23',
    messagingSenderId: '1038188114074',
    projectId: 'rndvouz-uh',
    storageBucket: 'rndvouz-uh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnXpJwHrTMZ2ikjo3taSWma7iEWmc1WQc',
    appId: '1:1038188114074:ios:376ad968e44d7f5e72af23',
    messagingSenderId: '1038188114074',
    projectId: 'rndvouz-uh',
    storageBucket: 'rndvouz-uh.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
