import 'package:app/data_model/measurements.dart';

import 'merchandise_garment.dart';
import 'merchandise.dart';
import 'merchandise_style.dart';

class MerchandiseDB {
  static List<Merchandise> loadMerchanise(Garment garment) {
    List<Merchandise> allGarments = <Merchandise>[
      Merchandise(
        id: 0,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.casual,
        garment: Garment.signup,
        merchColors: {MerchColors.green},
        merchName: "Casual Butterfly Flower Tube Top",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 1,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.classic,
        garment: Garment.jacket,
        merchColors: {MerchColors.black, MerchColors.white},
        merchName: "Black Jacket Vest",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 2,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.edgy,
        secondaryStyle: SecondaryStyle.casual,
        garment: Garment.tshirt,
        merchColors: {MerchColors.beige},
        merchName: "Cozy Beige Jacket",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 3,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.edgy,
        secondaryStyle: SecondaryStyle.casual,
        garment: Garment.tshirt,
        merchColors: {MerchColors.black, MerchColors.white},
        merchName: "White Japanese Art T-Shirt",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 4,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.casual,
        garment: Garment.jeans,
        merchColors: {MerchColors.blue},
        merchName: "Casual Loose Fit Ripped Jeans",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 5,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.preppy,
        secondaryStyle: SecondaryStyle.casual,
        garment: Garment.skirt,
        merchColors: {MerchColors.white},
        merchName: "Preppy White Skirt",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 6,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.chic,
        secondaryStyle: SecondaryStyle.formal,
        garment: Garment.jacket,
        merchColors: {MerchColors.tan},
        merchName: "Chic Khaki Coat",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 7,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.bohemeian,
        // dress
        garment: Garment.signup,
        merchColors: {MerchColors.blue, MerchColors.orange, MerchColors.beige},
        merchName: "Bohemian Flowy Summer Dress",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 8,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.bohemeian,
        secondaryStyle: SecondaryStyle.vintage,
        garment: Garment.jacket,
        merchColors: {MerchColors.tan, MerchColors.brown},
        merchName: "Bohemian Warm Fall Outer Coat",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 9,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.hipster,
        secondaryStyle: SecondaryStyle.casual,
        garment: Garment.longsleeve,
        merchColors: {MerchColors.yellow, MerchColors.black},
        merchName: "Yellow Plaid Oversized Longsleeve",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 10,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.elegant,
        secondaryStyle: SecondaryStyle.casual,
        garment: Garment.signup,
        merchColors: {MerchColors.black},
        merchName: "Cute Black Elegant Button-Up Dress",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 11,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.athleisure,
        secondaryStyle: SecondaryStyle.casual,
        // pants
        garment: Garment.signup,
        merchColors: {MerchColors.orange},
        merchName: "Copper Athletic Pants",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 12,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.western,
        garment: Garment.longsleeve,
        merchColors: {MerchColors.brown, MerchColors.yellow},
        merchName: "Button-Down Patterned Longsleeve",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 13,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.edgy,
        secondaryStyle: SecondaryStyle.streetwear,
        garment: Garment.pants,
        merchColors: {MerchColors.black},
        merchName: "Black Edgy Streetwear Chained Pants",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 14,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.preppy,
        secondaryStyle: SecondaryStyle.casual,
        // longsleeve
        garment: Garment.signup,
        merchColors: {MerchColors.black, MerchColors.white},
        merchName: "Cute Preppy Longsleeve with White Collar",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 15,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.preppy,
        // skirt
        garment: Garment.signup,
        merchColors: {MerchColors.yellow, MerchColors.black},
        merchName: "Preppy Edgy Yellow Plaid Skirt",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 16,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.casual,
        garment: Garment.shorts,
        merchName: "Blue Shorts",
        merchColors: {MerchColors.blue},
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 17,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.electic,
        secondaryStyle: SecondaryStyle.vintage,
        // longsleeve
        garment: Garment.signup,
        merchName: "Electic Jacket",
        merchColors: {
          MerchColors.green,
          MerchColors.orange,
          MerchColors.yellow
        },
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 18,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.vintage,
        secondaryStyle: SecondaryStyle.casual,
        garment: Garment.jacket,
        merchColors: {
          MerchColors.white,
          MerchColors.blue,
          MerchColors.green,
          MerchColors.orange
        },
        merchName: "Vintage Jacket",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 19,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.casual,
        garment: Garment.tshirt,
        merchColors: {MerchColors.white},
        merchName: "Cute Casual T-Shirt",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 20,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.businessCasual,
        merchColors: {MerchColors.blue},
        garment: Garment.longsleeve,
        merchName: "Basic Business Casual Button-Down",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 21,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.casual,
        garment: Garment.top,
        merchColors: {MerchColors.black},
        merchName: "Black Casual Top",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 22,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.casual,
        // longsleeve
        garment: Garment.signup,
        merchColors: {MerchColors.black},
        merchName: "Basic Simple Retro Crewneck",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 23,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.streetwear,
        garment: Garment.jacket,
        merchColors: {MerchColors.black},
        merchName: "Black Streetwear Jacket",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 24,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.minimalist,
        garment: Garment.pants,
        merchColors: {MerchColors.black},
        merchName: "Black Chic Pants",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 25,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.retro,
        secondaryStyle: SecondaryStyle.vintage,
        garment: Garment.longsleeve,
        merchColors: {MerchColors.white, MerchColors.blue, MerchColors.green},
        merchName: "Retro Colorful Longsleeve",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 26,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.casual,
        garment: Garment.top,
        merchColors: {MerchColors.green},
        merchName: "Casual Cute Green Knit Top",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 27,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.casual,
        secondaryStyle: SecondaryStyle.minimalist,
        garment: Garment.longsleeve,
        merchColors: {MerchColors.beige},
        merchName: "Casual Minimal Sweater",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 28,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.casual,
        garment: Garment.tshirt,
        merchColors: {MerchColors.white},
        merchName: "Casual White T-Shirt",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 29,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.classic,
        garment: Garment.jacket,
        merchColors: {MerchColors.green},
        merchName: "Classic Long Coat",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 30,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.casual,
        garment: Garment.top,
        merchColors: {MerchColors.blue, MerchColors.white},
        merchName: "Classic Cute Blue Tub Top",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 31,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.formal,
        secondaryStyle: SecondaryStyle.classic,
        garment: Garment.dress,
        merchColors: {MerchColors.black},
        merchName: "Formal Simple Black Dress",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 32,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.casual,
        garment: Garment.top,
        merchColors: {MerchColors.purple},
        merchName: "Tight-Knite Casual Top",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 33,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.loungewear,
        // longsleeve
        garment: Garment.signup,
        merchColors: {MerchColors.white},
        merchName: "Loungewear Cream Longsleeve",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 34,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.formal,
        garment: Garment.dress,
        merchColors: {MerchColors.black},
        merchName: "Short Black Formal Dress",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 35,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.outdoors,
        garment: Garment.pants,
        merchColors: {MerchColors.purple},
        merchName: "Purple Outdoor Pants",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 36,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.streetwear,
        garment: Garment.jacket,
        merchColors: {MerchColors.black},
        merchName: "Black Functional Street Jacket",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 37,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.casual,
        garment: Garment.top,
        merchColors: {MerchColors.green},
        merchName: "Green Tank Top",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 38,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.businessCasual,
        garment: Garment.longsleeve,
        merchColors: {MerchColors.white},
        merchName: "Formal White Button-Down",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
      Merchandise(
        id: 39,
        ownerUsername: "test",
        state: Availability.selling,
        primaryStyle: PrimaryStyle.streetwear,
        garment: Garment.tshirt,
        merchColors: {MerchColors.yellow},
        merchName: "Dirty Mustard Yellow Street T-Shirt",
        merchMeasurements: Measurements(
          bust: 20.0,
        ),
        sellingMethod: SellingMethod.selling,
        price: 13,
        likes: 40,
      ),
    ];

    if (garment == Garment.all) {
      return allGarments;
    } else {
      return allGarments.where((Merchandise m) {
        return m.garment == garment;
      }).toList();
    }
  }
}
